name: .NET Core Desktop

on:
  push:
    branches: [ "master", "develop" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      project: YetAnotherMifareTool/YetAnotherMifareTool.csproj
      zip: YetAnotherMifareTool

    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0

    # Install zip
    - name: Install zip
      run: sudo apt-get update && sudo apt-get install -y zip

    # Install the .NET Core workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore /p:EnableWindowsTargeting=true

    # Publish
    - name: Publish
      run: dotnet publish ${{github.workspace}}/${{env.project}} -o ${{github.workspace}} -c Release -f net6.0-windows -r win-x64 --no-self-contained --no-restore /p:PublishSingleFile=true /p:EnableWindowsTargeting=true

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{github.event.repository.name}}-${{github.sha}}
        path: |
          *.exe
          *.dll

    # Zip release
    - name: Zip release
      if: startsWith(github.ref, 'refs/tags/')
      run: zip -r "${{env.zip}}_${{github.ref_name}}.zip" *.exe *.dll

    # Upload release zip
    - name: Upload tagged release zip
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        files: ${{env.zip}}_${{github.ref_name}}.zip
